version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenhouse-beneficios
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - greenhouse_uploads:/app/uploads
      - greenhouse_db:/app/prisma/data
    environment:
      - NODE_ENV=production
      - EVOLUTION_API_URL=http://evolution:8080 # Ajuste conforme seu portainer
      - EVOLUTION_API_KEY=sua_chave_aqui
      - DATABASE_URL=file:/app/prisma/data/dev.db

volumes:
  greenhouse_uploads:
  greenhouse_db:
