version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: greenhouse-dev
    ports:
      - "3000:3000"
    volumes:
      # Mapeia o código fonte local para dentro do container
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
