version: "3.7"

services:
  web:
    image: ghcr.io/fontesmidias/greenhouse-beneficios:latest
    networks:
      - unibotnet
    volumes:
      - greenhouse_data:/app/data
      - greenhouse_uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=https://${DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EVO_SERVER_URL=${EVO_SERVER_URL}
      - EVO_GLOBAL_KEY=${EVO_GLOBAL_KEY}
      - EVO_INSTANCE_NAME=${EVO_INSTANCE_NAME}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.greenhouse-beneficios.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.greenhouse-beneficios.entrypoints=websecure"
        - "traefik.http.routers.greenhouse-beneficios.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.greenhouse-beneficios.loadbalancer.server.port=3000"

volumes:
  greenhouse_data:
  greenhouse_uploads:

networks:
  unibotnet:
    external: true
    name: unibotnet
